### ISSUE TITLE
Revamp Complete Beginner Guide

### ISSUE THREAD

**Issue by acnagy** [travis-ci/docs-travis-ci-com#1145]
We want to rework this page: https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/for-beginners.md to being more about new user orientation, i.e. the concepts folks need in order to get started/understand the rest of the docs. I'm thinking we should cover:

* What is CI? 
* What you can do with a build (compile, test, deploy) (in general)
* Jobs vs. Builds
* Travis CI vs. Travis Pro (`.org` vs. `.com`) 
* Breaking the build (status)
* Brief intro to our infrastructures (some of the https://github.com/travis-ci/docs-travis-ci-com/blob/gh-pages/user/ci-environment.md page might fit here)

Other things?

**Comment by acnagy** [comment]
More topics to add:
 * Build Stages can be added into `what you can do with a build` 
 * Build statuses + "breaking the build"

**Comment by acnagy** [comment]
Ok, I started my PR - https://github.com/travis-ci/docs-travis-ci-com/pull/1176 ... however, I'm stumped on the "Breaking the Build" section... what are we moving here? Should we break up the big "breaking the build" page we have? @plaindocs let's discuss...

**Comment by vagnerr** [comment]
**Heads up:** @acnagy While I'm sure you are going to notice it during your re-write, the current simple example no longer builds clean due to dropping of HHVM support by Ubuntu. Not sure how long its not worked for. I did try a couple of earlier dist versions before eventually just dropping HHVM from the php list. 

Might serve as a useful example though. Its not always your code that breaks the CI build the infrastructure can also move on.

**Comment by plaindocs** [comment]
#1176 is merged, so I'm closing this.
