### ISSUE TITLE
Default MySQL version not listed

### ISSUE THREAD

**Issue by rennat** [travis-ci/docs-travis-ci-com#1236]

**Comment by BanzaiMan** [comment]
Where do you expect to see this?

**Comment by rennat** [comment]
https://docs.travis-ci.com/user/database-setup/#MySQL

**Comment by cdemyanovich** [comment]
I agree with @rennat. I was looking for this information earlier today. I guessed that 5.5 is the current version based on the presence of the "MySQL 5.6" section. It seems that I guessed correctly, since switching to 5.6 solved my [problem](http://www.oyewiki.com/tech/incorrect-table-definition-there-can-be-only-one-timestamp-column).

**Comment by logannc** [comment]
It now appears that 5.6 is the default which makes the above comment and documentation very confusing.

**Comment by cdemyanovich** [comment]
Agreed. We could avoid this confusion if the version were documented at https://docs.travis-ci.com/user/database-setup/#MySQL. We could probably submit a documentation patch.

**Comment by logannc** [comment]
It should also be added to https://docs.travis-ci.com/user/reference/trusty/ as it is installed by missing from the list of DB services preinstalled.
