### ISSUE TITLE
'At a glance' box for language pages

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#1252]
Hey @lislis 

What do you think about a side box for the Language pages? Kinda like wikipedia has (https://en.wikipedia.org/wiki/Cascading_Style_Sheets) where we list default install, script, etc commands, whether it is community supported, etc.

If we throw in a markdown (or html if necessary) with a specific class can you figure out how it should look?

**Comment by lislis** [comment]
@plaindocs good idea! A class is all I need :D

**Comment by plaindocs** [comment]
From looking at Ruby, I'm thinking something like

Test | Test
-------------------|------------------
Test script        | `rake` 
Dependencies |  `bundle install --jobs=3 --retry=3` 
Matrix              | env, rvm, gemfile, and jdk 
Support           | Travis CI 
Example          | shortish .travis.yml example 

Although I suspect we *can't* put a code block in a table easily.

@acnagy any thoughts or additions to this

**Comment by acnagy** [comment]
@plaindocs @lislis this is a great idea! Maybe `Support: Travis CI` should be phrased differently? That's the only thing that caught my eye. 

Potentially we could also include container-based image, like @BanzaiMan did [here](1)  I had one person in :sapphire2: respond to your survey since we did your review and I added to the document. You should be able to just view revision history and see the changes.). That said, I'm not sure it's a great idea to include troubleshooting details alongside general info

**Comment by acnagy** [comment]
@plaindocs @lislis This is a great idea! Perhaps we could change the wording on `Support: Travis CI`, since that caught my eye.

Also, potentially we could include the container image, similar to what @BanzaiMan did [here](https://github.com/travis-ci/docs-travis-ci-com/blob/master/user/common-build-problems.md#running-a-container-based-docker-image-locally)... though I hesitate about include troubleshooting tips there with the general information on the language

**Comment by plaindocs** [comment]
Is that the link you intended to send? I'm not quite sure what you mean? re container stuff

Yeah, agree on the wording. How do you suggest we distinguish between Community Support and Official Support?

**Comment by acnagy** [comment]
@plaindocs Yup, that's the one - it's a bit clearer on the rendered docs which shows an actual table with info - https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally. Many supported languages are routed to one of two container images - either `ci-garnet` or `ci-amethyst`. If someone need to troubleshoot something, you can pull that particular email and have at it... which is why I thought that might be helpful. Still... I'm on the fence about whether this information should live in this table. 

As to the wording... pulling from what you just wrote `Language Support: Official` and `Language Support: Community` would work 😄  For the community ones, we could link to the page on community support and/or include the github handles of the maintainers

**Comment by plaindocs** [comment]
Ah, with you now. There was some display issue with another link before. I'd rather avoid that I think - it doesn't seem useful to the majority, without context. 

Yes yes yes on the language stuff.

**Comment by lislis** [comment]
Also looping in @ctrlaltjustine for some upcoming design decisions

**Comment by ctrlaltjustine** [comment]
I'm not entirely sure what you need for this design task. Could you please elaborate on your request/vision @plaindocs? Thanks!

**Comment by plaindocs** [comment]
@ctrlaltjustine 
![glancebox](https://user-images.githubusercontent.com/95874/27692203-6211fe66-5ce6-11e7-94b7-422c998652b1.png)
 I'd like to add an 'at a glance box' like the one on the right side of https://en.wikipedia.org/wiki/Cascading_Style_Sheets to our language pages.

So we'd need design / CSS for that. 

I can either add a class to a table, or use an html span around a table and a code block

Does that make any more sense?

**Comment by ctrlaltjustine** [comment]
@plaindocs something like this (created with the ruby example you gave above)?

![screen shot 2017-07-10 at 1 12 46 pm](https://user-images.githubusercontent.com/823381/28032808-875d4d54-6571-11e7-8724-aed1136a6680.png)

**Comment by plaindocs** [comment]
Looks awesome!

Third line would be `env`, `rvm`, `gemfile` and `jdk` 

but that is unlikely to change the whole thing.

**Comment by BanzaiMan** [comment]
I love the idea.

However, what goes in the table is up for debate. Listing the default values is useful, but the list will not be exhaustive, as the defaults change depending on the repository's structure; for example, we append `--deployment` to `bundle install` if `Gemfile.lock` exists in the repository root.

Some suggestions:

|    | Default |
|:--|:-------|
| Typical `install`| `bundle install --jobs=3 --retry=3`|
| Typical `script`| `rake`|
| Matrix keys | `env`, `rvm`, `gemfile`, `jdk` |
| Support | Travis CI |
| Example | ** |

1. Instead of "Test script" and "Dependencies", show what build phase takes on the values shown.
1. In the matrix keys field, avoid "and" (and the entire question of the Oxford comma).
1. In "Language support", eschew "Official", but instead show who is responsible for providing support.

**Comment by ctrlaltjustine** [comment]
Cool, if that design is acceptable, it shouldn't change based on content:

Here are the table styles:

### Table Global
```
border: 1px solid #f1f1f1;
border-radius: 2px;
padding: 10px;
```

### Table Title Cells
```
font-size: 10px;
color: #9ea3a8;
```

### Table Content Cells
```
font-size: 14px;
color: #666666;
```

**Comment by plaindocs** [comment]
@ctrlaltjustine @BanzaiMan :+1: :+1:

**Comment by plaindocs** [comment]
OK, so to have the code block as part of this, I think I'll need to have something like this:

```
<div markdown="block" class="ataglance">

|                   | Default                             |
|:------------------|:------------------------------------|
| Typical `install` | `bundle install --jobs=3 --retry=3` |
| Typical `script`  | `rake`                              |
| Matrix keys       | `env`, `rvm`, `gemfile`, `jdk`      |
| Support           | Travis CI                           |

\`\`\`yaml
language: ruby
rvm:
  - 2.2
  - jruby
  - 2.0.0-p247
\`\`\`

</div>
```

Which turns into 

```
<div class="ataglance">

  <table>
    <thead>
      <tr>
        <th style="text-align: left"> </th>
        <th style="text-align: left">Default</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="text-align: left">Typical <code class="highlighter-rouge">install</code></td>
        <td style="text-align: left"><code class="highlighter-rouge">bundle install --jobs=3 --retry=3</code></td>
      </tr>
      <tr>
        <td style="text-align: left">Typical <code class="highlighter-rouge">script</code></td>
        <td style="text-align: left"><code class="highlighter-rouge">rake</code></td>
      </tr>
      <tr>
        <td style="text-align: left">Matrix keys</td>
        <td style="text-align: left"><code class="highlighter-rouge">env</code>, <code class="highlighter-rouge">rvm</code>, <code class="highlighter-rouge">gemfile</code>, <code class="highlighter-rouge">jdk</code></td>
      </tr>
      <tr>
        <td style="text-align: left">Support</td>
        <td style="text-align: left">Travis CI</td>
      </tr>
    </tbody>
  </table>

  <div class="language-yaml highlighter-rouge"><pre class="highlight"><code><span class="s">language</span><span class="pi">:</span> <span class="s">ruby</span>
<span class="s">rvm</span><span class="pi">:</span>
  <span class="pi">-</span> <span class="s">2.2</span>
  <span class="pi">-</span> <span class="s">jruby</span>
  <span class="pi">-</span> <span class="s">2.0.0-p247</span>
</code></pre>
  </div>

</div>
```

**Comment by plaindocs** [comment]
Can we easily float this right with our current layout? 

There is a version in the wild, although not yet live at 391acb56

**Comment by ctrlaltjustine** [comment]
I reckon, floating it right is the best option.

**Comment by lislis** [comment]
https://github.com/travis-ci/docs-travis-ci-com/pull/1327

**Comment by plaindocs** [comment]
Thank you both for all the work on this! Merged!
