### ISSUE TITLE
Add an introduction guide/walk-through to show how to set up and run a simple project

### ISSUE THREAD

**Issue by roidrage** [travis-ci/docs-travis-ci-com#134]
@brntbeer asked for a nice little introduction guide to walk people through the steps of setting up a simple build project. I think this is a great idea, and he wanted to add a few things he'd like to see, so this is the place to be (hey, that rhymed).

**Comment by roidrage** [comment]
Paging @brntbeer!

**Comment by brntbeer** [comment]
I'm the worst. sorry for majorly dropping the ball on this.

For a guide / walkthrough on this, i think the most important piece is: what is the goal? For me, the goal isn't really to teach someone programming (though they'll need to know a bit per language), it isn't to teach someone how to use Git. It's to teach them WHY you want testing and how EASY travis is. I guess my idea is as follows:

## First run
- fork `travis-ci/example-ruby` or similar repository
- Connect travis-ci to this repository
- (Somehow) get the student to open a pull request, maybe something as simple as changing the output of something to include their name? The problem here is multiple people forking and updating and offering PRs. Probably need to ensure they send the PR to themselves, NOT back to `travis-ci/example-ruby`
- Tests will fail
- student updates code to fix test
- Tests pass, merge PR. :tada:

The guide on the travis docs site will guide them through this, describing what to do. In a perfect world with infinite time, the answers for what to do for the failed tests aren't immediately viewable. I'd think the answers to make the tests pass are sort of just hidden on the page. "Click here to view answers" or something similar. 

By the end of the guide, the student will have hooked up travis to a repository of their liking, see what failing tests look like (and maybe the guide describes why tests are important?), and how changes are reflected / updated back in the PR for passing tests.

**Comment by plaindocs** [comment]
Alternatively you just have a separate example quickstart repo with broken code, missing ';' whatever, that you know will fail. In the quickstart you tell people how to fix it so it passes.
