### ISSUE TITLE
Add Angular test config to documentation

### ISSUE THREAD

**Issue by GuyHarwood** [travis-ci/docs-travis-ci-com#1367]
When deploying an Angular 4.x app it's not obvious how to configure `ng test` to run Chrome Headless.

Some guidelines would be great for both the karma config (for headless chrome) and the Chrome addon config, if necessary.

**Comment by GuyHarwood** [comment]
ignorance is bliss

**Comment by MariadeAnton** [comment]
Hi @GuyHarwood - Thanks so much for the re-ping here. 

Which kind of guide do you have in mind? Something along the lines of this blog post https://500tech.com/blog/all/running-travis-ci-unit-tests-using-google-chrome/ ? 

Also, were you able to configure `ng test` the way you wanted? If you could link us to your configuration so that we can test it out, it'd be extra helpful. Thanks again!

**Comment by GuyHarwood** [comment]
Hi @MariadeAnton, thanks for picking this up.

Yes, something similar to what you linked with basic guidelines on getting headless chrome setup in the travis yml file.

We ended up using headless chrome with ruby & cucumber to automate our angular app testing.

travis file, and associated repo here - https://github.com/DFEAGILEDEVOPS/MTC/blob/master/.travis.yml
