### ISSUE TITLE
addons: ssh_known_hosts Doesn't allow environment variables

### ISSUE THREAD

**Issue by cawka** [travis-ci/docs-travis-ci-com#1416]
In my setup I would like to use deployment hostname from environment variable and somehow addons: ssh_known_host doesn't allow that.

This simple config

```yaml
addons:
    ssh_known_hosts: $HOSTNAME
```

resulted in this error:

```
$ ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H \$HOSTNAME 2>&1 | tee -a $HOME/.ssh/known_hosts
```

**Comment by BanzaiMan** [comment]
This is not a documentation issue, so https://github.com/travis-ci/travis-ci is more appropriate.

Unless the value you want to set is pre-defined by the shell (quite unlikely), this is not going to work because `ssh_known_hosts` is executed before user-defined environment variables are available. `ssh_known_hosts` needs the root privilege to work, which must precede env var `export`s.

**Comment by BanzaiMan** [comment]
Actually, it does not require root privilege. Regardless, this is not a place to discuss it. Please open an issue at https://github.com/travis-ci/travis-ci/issues if you want to discuss this further.

**Comment by cawka** [comment]
My apologies. I didn't mean to open issue for documentation :)  I even checked existing issues about this before creating. Thanks for getting back on this quick.
