### ISSUE TITLE
Sidebar content for Enterprise section on the top page should have more quick links

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/docs-travis-ci-com#1610]
<img width="657" alt="travis_ci_user_documentation" src="https://user-images.githubusercontent.com/25666/34116177-c9f12ec2-e3e5-11e7-8366-f9481182ccca.png">

The should closely reflect the Enterprise section:

<img width="800" alt="travis_ci_enterprise_-_travis_ci" src="https://user-images.githubusercontent.com/25666/34116251-0953f5c2-e3e6-11e7-8ffd-69f6e28502f3.png">

**Comment by acnagy** [comment]
Hmm... this is a good point, like, it's by design, but it's supposed to be helpful UX not "why did these links appear" UX. I'd be all for changing it - maybe links should be to directories of docs only visible on the Enterprise page... which means, I guess we need directories? 🤔 

🔔 @plaindocs @bnferguson @danishkhan @mariana-gu @schultyy Do you have opinions?

**Comment by plaindocs** [comment]
Yeah, this was always something of a band aid till we get a better Enterprise redesign.

I can easily add the same Enterprise list in the main docs menu. Do you think it would then be confusing to lose the rest of the docs menu, when clicking on a link. Or just the same as now?
