### ISSUE TITLE
Regexp usage in YAML conditions

### ISSUE THREAD

**Issue by iriberri** [travis-ci/docs-travis-ci-com#1793]
Regexps can be used in different parts of the .travis.yml, but their usage in the different sections of the configuration is not consistent:

- https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches shows how to filter branches, and uses \d.
- https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A shows how to set conditions for deployment, and does not support \d ([0-9] needs to be used instead)

While this is something that should probably be made consistent in the product, it'd be great to clarify in the docs the type of regexps that work in each case, maybe with a small note and/or example.

**Comment by BanzaiMan** [comment]
Consistency is not possible, due to the differences in regular expression engines in effect at different parts of the system. Some are processed by Ruby (processing branch names in gatekeeper and scheduler), and some are processed by Bash (deploy conditions). The former is a lot more expressive than the latter.

The best we can do is explain what "regular expression" means in each of these cases, and give examples.
