### ISSUE TITLE
Comprehensive reference for travis.yml syntax and keywords?

### ISSUE THREAD

**Issue by maphew** [travis-ci/docs-travis-ci-com#2004]
Is there a single reference document or page for all the keywords allowed in `.travis.yml` and their meaning and usage?

**Comment by Hanse00** [comment]
Having recently taken up Travis myself, it could very well be user error. But I'm indeed also confused about how to combine the various values possible. One article will give a code block that makes sense, and so will another, but when trying to use the two together, it's not clear how to combine them.

A comprehensive list of which keywords are allowed globally, and as sub commands to other keywords would be extraordinarily helpful.

**Comment by Azhrei** [comment]
+1

I'm _not_ new to Travis and I still have a hard time putting the various pieces together.  It's particularly frustrating when the documentation is wrong or incomplete. :(

**Comment by codytwinton** [comment]
+1

**Comment by Amit-A** [comment]
+1

**Comment by yapcwed** [comment]
There's the [JSON Schema](http://json.schemastore.org/travis) that is used by various [editors](http://schemastore.org/json#editors). E.g. VSCode with the [YAML Package](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml).

**Comment by Azhrei** [comment]
Hm, that's useful.  Thanks!  (No excuse for the lack of documentation by this project, however.)

**Comment by codytwinton** [comment]
@yapcwed didn’t say it was an excuse. This is an open source project, so we’re all welcome to contribute to the documentation.

**Comment by Azhrei** [comment]
Sorry, I didn't mean any offense to @yapcwed.  In fact, I'm very grateful that he posted the link to the JSON schema.  It's the most concise description of what options are allowed that I've seen.

But a syntax highlighting configuration file doesn't really help much towards figuring out what combinations of options can be used. :(

**Comment by yapcwed** [comment]
No offense taken @Azhrei. I simply wanted to point out that this reference exists. To be honest I was hoping for someone from the travis team (or anyone else familiar enough with JSON Schema and travis) to see this and consider improving it/ adding it to the documentation.

**Comment by plaindocs** [comment]
Hey @yapcwed I wasn't aware of the schema, but will take a look. Thanks for the link.

**Comment by TravisCarden** [comment]
Thanks for pointing out [the JSON schema](http://json.schemastore.org/travis), @yapcwed. That's very helpful. Would the maintainers consider linking to it from the documentation, or--even better--creating a quick reference guide to it? When I got started, I looked for a page devoted to `.travis.yml` and was surprised to find nothing official. I searched for things like ".travis.yml schema", "example .travis.yml", "comprehensive .travis.yml", and ".travis.yml reference". If there were something analagous to [The Composer Cheat Sheet for developers](https://composer.json.jolicode.com/) for `.travis.yml`, I would _still_ consult it frequently.

**Comment by rokcarl** [comment]
It's one of the first things I searched for as I'm used to other `.yml` configuration files.

Check how this should be done: GitLab's [`.gitlab-ci.yml` reference](https://docs.gitlab.com/ee/ci/yaml/).

I've found https://devhints.io/travis pretty useful, far from perfect though.

**Comment by Azhrei** [comment]
Wow, that's awesome.  I may need to look into GitLab instead of GitHub.  Thanks for the link. 👍

**Comment by svenfuchs** [comment]
FWIW we now export our build config specification as a JSON Schema https://github.com/travis-ci/travis-yml/blob/master/schema.json

This library will be, but is not yet, fully, in use in production, unless you opt in, but it should be fairly complete in terms of keywords. We are looking into generating reference documentation from this schema to publish on our docs.

**Comment by ambroiseRabier** [comment]
+1

**Comment by Azhrei** [comment]
That's a great start — thanks!

s someone who has tried to setup a Travis configuration from scratch, I find the biggest problems are:  knowing the functionality behind each keyword, and knowing the interactions between those keywords.  This new document seems to help with the former, at least.  (Although just browsing for questions I've had in the past, I checked how this document details secure environment variables and found it... lacking.  The examples on the "env" page are duplicated and the "Secure" link under Types doesn't actually document how secure variables work as they're not mentioned on the Types page at all.  I consider these kind of minor, though, as this is just a first draft.)

**Comment by SuperSandro2000** [comment]
Spam bot

**Comment by svenfuchs** [comment]
@Azhrei thanks for the feedback. i've wanted to pick this up again, and checked for the duplicate env examples you mentioned, but i do not see any. these all look unique: https://config.travis-ci.com/ref/env . could you clarify? (maybe the issue was somehow fixed in the meantime ... just asking to see if i am missing something)

**Comment by Azhrei** [comment]
Hm.  Sorry, Sven, I don't really recall.  Visiting that page now, I see that there are some seemingly useless examples.  For example, the first one defines `FOO: foo` in two different spots.  What's the point?  Perhaps they should be `FOO: 'this is global'` for the first one and a different string for the second?

I don't know that's what I meant by "duplicated", but I honestly don't recall now.  Since I don't have access to any history for the page, and the WaybackMachine doesn't have it, I can't tell if there used to be different text there. :(

**Comment by svenfuchs** [comment]
@Azhrei  that's alright, no worries. i just wanted to double check.

> I see that there are some seemingly useless examples

they may seem so, i agree. this just lists various allowed forms (many of which people are actually using, even if not documented otherwise). i understand this might be too much, but since all this is autogenerated from the schema, and autogenerating things is ... kinda hard :) ... i'm not sure how much this can be improved easily. i'll still have a look if i can reduce this in a reasonable way.

thanks for all the feedback!

**Comment by SuperSandro2000** [comment]
bump cause stale bot
