### ISSUE TITLE
Feedback form formatting

### ISSUE THREAD

**Issue by plaindocs** [travis-ci/docs-travis-ci-com#2230]
I'd like to sling one of these on every page, but looking somewhat better than this:

Some kind of thumbs up / thumbs down answer to Was this helpful? IF no then show the message box.

Could be at the end of the page (not ideal), potentially *very* unobtrusively at the end of each section, or possibly floating although that might get annoying.  

Any thoughts? 

![image](https://user-images.githubusercontent.com/95874/51135959-eefaef00-1800-11e9-9967-b29ed035c152.png)

For example on the microsoft docs they float a footer:

![image](https://user-images.githubusercontent.com/95874/51136445-228a4900-1802-11e9-9199-282131b5759b.png)

from https://support.office.com/en-us/article/how-do-i-tell-where-my-yammer-files-are-being-stored-fadfdefa-e00d-40b6-94cb-a9ddb171a443

@MariadeAnton @paulthegeek

**Comment by plaindocs** [comment]
100%, only show the box on "No"

So I tested Netlify forms, which works amazingly well. And then was going to tie Zapier in to add things to a spreadsheet in gdocs. 

But that would require moving our production env to Netlify, which I'm in favor of, (but would need a teensy bit more research). 

Otherwise I can just a form to email SaaS solution, and parse that into a spreadsheet with Zapier. 

Both low time low cost options.

**Comment by artursmirnov** [comment]
Hey @plaindocs, that's a great idea! 

Although, I'm not sure these widgets work in most cases. E.g., to be honest, I never clicked one of those buttons myself, no matter if it was helpful or not. If it was useful, I usually switch to solving a problem right away, otherwise - just close the page disappointed. Probably that's just me the ungrateful user, but I think that's the case for the most part of visitors. For me it's mostly because I, as a user, don't see any benefits for myself from this action. But what if we would make this widget unlock further conversation to user? Just by making it say "Didn't find a solution at this page? Let us know your problem and we will help!" We can consider it as "No" from initial widget variant and as a flag that this page may need some improvement. Also, by pressing this button, a user already want's to communicate and we can ask them more details, like "What was your problem?" and "How can we contact you to help?", which could help us understand, what exactly needs improvement (if needs at all, maybe it was just irrelevant search result).

What do you think?

**Comment by plaindocs** [comment]
Hey Artur, for sure. The plan is mostly to put it up, and see what the usage is. We get a lot of Pull Requests and issues for the docs, so some of those might translate to indications about the quality as well. 

I expect very few `Yes` options indeed. I've not thought about how we word the `further comments on NO` yet, but something like you suggest, although possibly without the contact details.
