### ISSUE TITLE
How to restrict build failure emails to only a CRON JOB in travis CI?

### ISSUE THREAD

**Issue by rhande-mdsol** [travis-ci/docs-travis-ci-com#2356]
I have email and slack notifications configured for travis build failures. Currently It sends notifications for build failure of every branch. Since every developer does creates lot of branches, the mails come in a large number which sound like spam. I would want to restrict the mails only for failures of CRON Jobs.

My configuration in .travis.yml is something like this.

notifications:
   email:
    recipients:
     - xyz@abc.com
    on_success: change
    on_failure: always

I tried adding a condition i.e. if type = cron, but did not work.

**Comment by MariadeAnton** [comment]
Thank you so much for opening this here @rhande-mdsol, right now there are conditional builds, stages, and jobs:  https://docs.travis-ci.com/user/conditional-builds-stages-jobs/  Being able to extend this to custom notifications like `on_condition:` sounds like a feature request rather than a documentation update. Could you please create a new topic for this at https://travis-ci.community/ ? Thanks again!
