### ISSUE TITLE
install: true

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/docs-travis-ci-com#2422]
The docs refer to `install: true` to disable the default installation routine.
https://github.com/travis-ci/docs-travis-ci-com/blob/19c540badf1544dfbbcbe1927854e05cd0e21288/user/job-lifecycle.md#skipping-the-installation-phase
`install: false` also works, and seems much more intuitive when reading it regarding what it will do.

And if there is an `install: true` at the top level, how does one re-instate the default install script for jobs in `matrix:` / `jobs:` ?  i.e. how to disabled inheriting `install: true` from the top level?

This would be more logical if `install: false` was used at the top level, and `install: true` was then used to use the default install script.

There are limited alternatives to add new syntax, as `install: default` currently means run `default`.

Of course switching the meaning of `install: true` would be a rude shock, but it might be more feasible in the future if the docs started recommending `install: false` now.

----

Related bug report, `env: false` doesnt work.  It results in the job failing to be parsed.  `env: {}` works to disable the env matrix in a job.  Also raised as https://travis-ci.community/t/env-false-breaks-job/4208

**Comment by native-api** [comment]
`install:` section is a command or a list of commands. `true` is a Linux command that always returns a success code. `false` a command that always returns a failure code which is undesirable.
This is why `install: true` is more logical here.

You can suggest an improvement to the documentation using a link on the top of a documentation page.

**Comment by BanzaiMan** [comment]
The passage in question should be rewritten to read `install: skip`, which actually skips the step. Because `install: true` technically does not.

<details>
<summary>Here's a more technical discussion. You can dismiss it at will.
</summary>
The `install` and `script` keys are meant to receive one or more commands to be executed during a job.

`install: false` causes the default `install` commands to be executed. This behavior is quite different from skipping it altogether, which is what the document describes. (The same is true for `script`.)

With `install: true`, on the other hand, the Boolean value `true` thus defined will end up in the build script compiler, which will pass this value to Bash, which will interpret it as the command `true`, which always exits with status 0, which is effectively skipping (but not technically).
</details>

---

> There are limited alternatives to add new syntax, as `install: default` currently means run `default`.

What does this mean? Unless you have written a script named `default`, this is going to fail.

> Of course switching the meaning of `install: true` would be a rude shock, but it might be more feasible in the future if the docs started recommending `install: false` now.

This does not apply.

**Comment by jayvdb** [comment]
https://github.com/travis-ci/docs-travis-ci-com/blob/9c76f7bfa48559fc05c2ffefadf9cb4a2a77e9cd/user/build-stages/define-steps.md does mention `install: skip`

Using `install: skip` results in "Skipping the install step, as specified in the configuration."  Nice.  I havent seen that before now.  Yes that is better than `install: true`.

>> There are limited alternatives to add new syntax, as `install: default` currently means run `default`.
> What does this mean?

I mean that the ability to add new meanings, with enhancements to travis-build, are quite limited, because any string *could* be a valid command.  But travis has done this by adding meaning to `skip`. :+1:
