### ISSUE TITLE
dpl v2 Github pages provider commit_messages missing variables

### ISSUE THREAD

**Issue by adrianbroher** [travis-ci/docs-travis-ci-com#2675]
The current documentation of dpl notes a `commit_message` key, which allows to set the commit message.  The given example shows some variables in the format `%{identifier}`, but does not list which variables are available for substitution.

Reading the dpl code there seems also the possibility to use environment variables, but the syntax is never described anywhere.

**Comment by svenfuchs** [comment]
Thanks for pointing this out @adrianbroher. We haven't had introspection for interpolation variables on dpl v2 so far, but now we do: https://github.com/travis-ci/dpl/pull/1165

This should address your issue: https://github.com/travis-ci/docs-travis-ci-com/pull/2677. Pending a review on the PR i'll close your issue here. Please feel free to reopen it if needed.
