### ISSUE TITLE
dpl - unrecognised message code skip_job undocumented

### ISSUE THREAD

**Issue by mymindstorm** [travis-ci/docs-travis-ci-com#2734]
![image](https://user-images.githubusercontent.com/27789806/77585821-26f4cc00-6eb3-11ea-8f5e-550304cecbd6.png)

I don't have a key called `skip_job` in my .travis.yml. This error is not documented on the [build config validation page](https://docs.travis-ci.com/user/build-config-validation/#skip_job).

Build with message: https://travis-ci.com/github/Authenticator-Extension/Authenticator/builds/155226287/config

**Comment by svenfuchs** [comment]
@mymindstorm wow, that is correct. thanks for the report. this is a new message that is now being produced, and we've missed adding it to the UI. i'll make sure we add it.

the message is being produced if we filter out a job from your build matrix due to a condition you have specified on `jobs.include`.

**Comment by svenfuchs** [comment]
added to the UI here: https://github.com/travis-ci/travis-web/pull/2423, and the docs here: https://github.com/travis-ci/docs-travis-ci-com/pull/2738

thanks again for the report!
