### ISSUE TITLE
Build is still failing

### ISSUE THREAD

**Issue by upcwangying** [travis-ci/docs-travis-ci-com#2801]
[build](https://travis-ci.org/github/chenyifaerfans/chenyifaerfans)

I have a issue when using Travis, how to solve it?

**Comment by Pezi777** [comment]
Hey, we are trying to answer questions like this on the [community forum](https://travis-ci.community), because other users might have similar problems and we’d like to have them more discoverable and more visible to the community. Could you please go there and ask your question or contact our [support team]( support@travis-ci.com)?
