### ISSUE TITLE
setting up environment variables in travis

### ISSUE THREAD

**Issue by SolarUltima** [travis-ci/docs-travis-ci-com#2820]
hello I'm building a React app, In my react app I have environment variables which I am acessing using process.env that looks Something like this:

```
firebase.initializeApp({
  apiKey: process.env.REACT_APP_API_KEY,
  authDomain: process.env.REACT_APP_AUTH_DOMAIN,
  databaseURL: process.env.REACT_APP_DATABASE_URL,
  projectId: process.env.REACT_APP_PROJECT_ID,
  storageBucket: process.env.REACT_APP_STORAGE_BUCKET,
  messagingSenderId: process.env.REACT_APP_MESSANGER_ID,
  appId: process.env.REACT_APP_ID,
  measurementId: process.env.REACT_APP_MEASUREMENT_ID,
});
```

Any help would be appreciated?

**Comment by Montana** [comment]
Hello @SolarUltima,

The most reliable way to encrypt something with the public key is to use Travis CLI. This tool is written in Ruby and published as a gem, that you can add to your project. First, you need to install the gem:

```ruby
gem install travis
```

You'll want to run the following in your project directory (obviously replacing your own values):

```bash
travis encrypt DB_URL=super_secret
```

If you are using [travis-ci.com](url) instead of [travis-ci.org](url), you need to login first:

```bash
travis login --pro
```

Then, you can use the `travis encrypt` command to encrypt data (This example assumes you are running the command in your project directory. If not, add -r owner/project, so this can execute properly):

```bash
travis encrypt SOMEVAR="secretvalue"
```
Alternatively, if you are using [travis-ci.com](url), you will need to add the--pro flag: 

```bash
travis encrypt --pro SOMEVAR="secretvalue"
```

The ```.travis.yml``` file will now contain an entry of:

```bash
env:
  secure: MBxG/gsqeyONzA7wbWKACzv...
```

Travis will decrypt this into the original key/value pair of:

```DB_URL=super_secret```.

Once the encrypted environment variable is added to the ```.travis.yml``` file you'll commit your changes and carry on with your normal process. Travis now has access to your environment variables and they'll remain secret from others even if your project repo is public. More info and options available in the [Travis CI environment variables docs.](url)

**Comment by Montana** [comment]
Marked this as I solved it, via also asked on forums.
