### ISSUE TITLE
Add docs on how to skip the install step

### ISSUE THREAD

**Issue by rkh** [travis-ci/docs-travis-ci-com#323]
`install: true` or `install: /bin/true` should do the trick, not sure where in the docs this should go

**Comment by b-long** [comment]
Just a thought, but perhaps it'd be helpful to explain what's going on by declaring `install: true`.  I'm guessing it's just returning `/bin/true` rather than invoking the language's default (e.g. `cabal install`, `mvn install`) ?  Maybe some additional text could explain that to a user, since I think the current text is a bit confusing.
