### ISSUE TITLE
Document how to deploy via Git

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#463]
More specifically how to setup an SSH key for this.

**Comment by plaindocs** [comment]
@cotsog you're talking about deploying to github releases? 

In there we currently only mention oauth tokens, not ssh keys. 

https://help.github.com/articles/creating-an-access-token-for-command-line-use/ ? 

So you want this 

https://gist.github.com/zhujunsan/a0becf82ade50ed06115
https://developer.github.com/v3/repos/keys/

as an alternative?

**Comment by cotsog** [comment]
This is the [original ticket](https://secure.helpscout.net/conversation/153642099/23731/?folderId=30788) that generated this issue.

**Comment by MariadeAnton** [comment]
There's a documented option to use a custom SSH key in Travis CI - https://docs.travis-ci.com/user/private-dependencies/#User-Key → This is a built-in option for private repositories. 

We'll be linking and extending this a bit on our deployment options via: https://github.com/travis-ci/docs-travis-ci-com/issues/1693

So that it's clear that adding a custom ssh key works for both fetching and uploading things through Git.

Thank you, @cotsog and @plaindocs!
