### ISSUE TITLE
s3 upload doesn't remove deleted files

### ISSUE THREAD

**Issue by bitsuns** [travis-ci/docs-travis-ci-com#519]
Upload to s3 doesn't remove deleted files. It appears to be only a push of the latest build, w/o removal.

**Comment by roidrage** [comment]
Thanks for reporting this. Could you elaborate on what you mean with "deleted files"? Are those files that were created as part of the build or files previously stored on S3?

**Comment by bitsons** [comment]
No problem. Files that were created in one build and not present in a subsequent build.

As mentioned by another user via http://continuousfailure.com/post/s3_blog/:

"Note, we chose to use s3cmd because the provided Travis CI S3 deploy step doesn’t allow you to actually ‘sync’. Meaning if files are removed from your blog, their deploy step doesn’t remove them, and all files are always uploaded to the bucket, even if they haven’t changed, slowing down the deploy, and costing you money."

**Comment by MariadeAnton** [comment]
@bitsuns, thanks for elaborating! 

I think I understand now, how would a note specifying that if there's any deprecated upload in the bucket it should be removed manually in S3 ?

**Comment by bitsuns** [comment]
No problem. Yes, adding that clarification would be good.

**Comment by mpharrigan** [comment]
This would be a nice feature to have, in addition to the doc clarification

**Comment by plaindocs** [comment]
I think that the doc fix #542 above fixes this. Please reopen if you have more comments.

**Comment by aladagemre** [comment]
I agree with @mpharrigan. Doc fix is a kind of workaround. I think there should be a delete parameter handling this. aws and s3cmd apps does delete non-existent files with --delete parameter:

    aws s3 sync  . s3://my-bucket/ --delete
    # or
    s3cmd sync --delete-removed  -P -M -r . s3://my-bucket/

**Comment by abeMedia** [comment]
I agree with @aladagemre! Having a delete option would be really useful and save manually having to check the bucket.

**Comment by BanzaiMan** [comment]
The feature requests should go to https://github.com/travis-ci/dpl/issues. This is for documentation fixes and suggestions.
