### ISSUE TITLE
Document the Default Language is Ruby

### ISSUE THREAD

**Issue by acnagy** [travis-ci/docs-travis-ci-com#862]
We received some feedback via support that the docs should be clearer (i.e. mention) that the default language for projects without a `language` section is Ruby. That said, I'm not 100% sure where to put it. All of the following seem reasonable to me..
 - Getting Started
 - CI for Complete Beginners
 - Ruby language page

@plaindocs do you have opinions on the best place to add a sentence/section on this? Thanks!

**Comment by BanzaiMan** [comment]
I have a different take on a case like this one. Users like this are probably not interested in reading documentation at all, but are expecting the build to work magically. I am doubtful that adding more documentation is going to help them.

Instead, we can communicate to them that we are using Ruby because they didn't perform the task *outside of* the documentation. That place, I believe, is the build logs.

**Comment by plaindocs** [comment]
I tend agree with @BanzaiMan here, definitely the build error/log. But that said I *should* be clear in the docs if it isn't already - so we can double check that as well.
