### ISSUE TITLE
Add a warning that some CLI tools can leak encrypted environment variables

### ISSUE THREAD

**Issue by cotsog** [travis-ci/docs-travis-ci-com#956]
Coming from [HS #48150](https://secure.helpscout.net/conversation/310646404/48150/?folderId=30784).

I think a warning could be added in [our documentation about encrypted environment variables](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml).

**Comment by plaindocs** [comment]
Thanks for raising this issue @cotsog .

Can I just clarify that we're talking about the source connect `verbose` (https://wiki.saucelabs.com/pages/viewpage.action?pageId=483657810 but that the real issue is that anything that "has access to" variables that are encrypted in `.travis.yml` could theoretically expose them.

So a note in the encrypted variables topic suggesting caution with flags "like" verbose is the way to go.

**Comment by cotsog** [comment]
@plaindocs: thanks for your input!

I confirm that we should add a general note about CLI tools possibly leaking encrypted environment variables in the build log.

The Sauce Connect CLI with the `verbose` is an instance of this issue.
